baseurl: "https://joaobazzo.netlify.app/"
languageCode: "en-us"
author: "João P. Bazzo Vieira"
title: "João P. Bazzo Vieira"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Research output
      url: "publications/"
      weight: 2 
    - name: Posts
      url: "post/"
      weight: 3 
    - name: CV
      url: "files/JPBV_CV_shortned.pdf"
      weight: 4
    # - name: Subscribe
    #   url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [João Bazzo](https://joaobazzo.netlify.app/) {Year} | [Github](https://github.com/joaobazzo) | [Twitter](https://twitter.com/joaopbazzo) | joao.bazzo@gmail.com"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
